# Generated by Django 4.2.3 on 2023-07-08 20:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('paymentapp', '0002_rename_name_product_manufacturer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, null=True),
        ),
    ]
