# Generated by Django 4.1.7 on 2023-09-27 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentapp', '0009_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
